name: CI to Docker Hub

on:
  # Triggers the workflow on push or pull request events but only for the feature/dockerise branch
  push:
    branches: [ feature/dockerise ]
  pull_request:
    branches: [ feature/dockerise ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Extract sanitised branch name
        shell: bash
        run: echo "##[set-output name=sanitised_branch;]$(get_sanitised_branch_name)"
        id: extract_branch

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/wake-on-lan-mqtt-proxy:${{steps.extract_branch.outputs.sanitised_branch}}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}


      